### ISSUE TITLE
Liquidity Distribution on-hover chart labels incorrect?

### ISSUE THREAD

**Issue by shazow** [Uniswap/uniswap-v3-info#37]
**Bug Description**

Maybe I'm misunderstanding what the on-hover tick chart label represents, but it seems it's implying that the peak liquidity slot for USDC/ETH is $8725. I would expect that the peak would be close to the current USDC/ETH value which is $3,585. Am I confusing what the prices represent, or are the label values incorrect?

The very right edge of the chart is $3590. (See screenshot below)

Also I'm not quite sure what the "USDC Price" represents there.

**Steps to Reproduce**

1. Go to https://info.uniswap.org/#/pools/0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8
2. Click on "Liquidity"
3. Hover on chart, observe that the label doesn't quite make sense...

**Expected Behavior**

The peak tick liquidity should be near the current price ratio of the pair? 

Bonus points if the chart had axis labels, to make it more screenshot sharing friendly when you want to do Thought Leading :tm: about Uniswap v3 liquidity charts as price prediction markets. :joy: 

**Additional Context**

![image](https://user-images.githubusercontent.com/6292/117480225-520f7300-af2f-11eb-8d80-605af2ba6173.png)

**Comment by shazow** [comment]
Looks like this was fixed, though some axis units would still be great. :)

**Comment by ianlapham** [comment]
Yep @shazow @chtmorris thanks for pointing this out. It was an issue of fetching stale data. Should fetch up to date always, and labels being added now. 

Will re-open if data seems incorrect again.
