### ISSUE TITLE
Show Fees in charts and summary stats for tokens and pools

### ISSUE THREAD

**Issue by ianlapham** [Uniswap/uniswap-v3-info#52]
- right now only pool page had dedicated annulaized fee stats  
- need to show this on pool tables 
- need to show this for tokens as well

**Comment by willhennessy** [comment]
how will we present the fees? Hard to annualize to an APY because that depends on the price range.

* Pool:  total $ of fees in the pool in the last 7 days?
* Token:  sum of fees generated across all pools containing this token?

**Comment by ianlapham** [comment]
@willhennessy 
- Correct for pools and tokens there - aside from APY those numbers are straightforward
- for APY we might need to make some assumptions that price stays in range
