### ISSUE TITLE
"/token/{token_address}" not showing pools even though they exist

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-v3-info#57]
**Bug Description**
User has position: https://app.uniswap.org/#/pool/16507
token: 0x7d29a64504629172a429e64183d6673b9dacbfce
but https://info.uniswap.org/#/tokens/0x7d29a64504629172a429e64183d6673b9dacbfce
doesn't show anything

**Steps to Reproduce**
Not sure what is causing this exactly. Might be:

 I've been doing some testing of my own, I'm seeing the reason is because the weth has been drained from the pool due to the price difference .. I have found that buying even the smallest amount will set it back into range... and then you could pull the LQ

**Expected Behavior**
It shows existing pools

**Comment by Rachel-Eichenberger** [comment]
wanted To Jump in Here,, a little confusion got two issues together

this quote
``` I've been doing some testing of my own, I'm seeing the reason is because the weth has been drained from the pool due to the price difference .. I have found that buying even the smallest amount will set it back into range... and then you could pull the LQ ``` 
was for a separate issue.. :) sorry for the confusion

This issue just seemed to not load the token 1/2 the time or more

**Comment by ianlapham** [comment]
Not exactly sure the issue here - https://info.uniswap.org/#/tokens/0x7d29a64504629172a429e64183d6673b9dacbfce
Does show a token page on info
