### ISSUE TITLE
Token Price does not get updated/

### ISSUE THREAD

**Issue by Pinatapins** [Uniswap/uniswap-v3-info#59]
We have a pool with almost 100k$ TVL pairing with ETH and with 40k$ volume still the value of the token doesn't show up.
furthermore, when we click on the token most of the time it shows no token exist even-though we have an active pool.

Improvements needed badly i think.
Uniswap is still the best tool ever.

Cheers.

**Comment by justindomingue** [comment]
@Pinatapins transfered to uniswap-v3-info

**Comment by Pinatapins** [comment]
Thank you,

Do you know when it may be fixed?

**Comment by justindomingue** [comment]
@ianlapham should be able to answer this

**Comment by ianlapham** [comment]
@Pinatapins This is happening because the threshold for ETH in the pool is higher than the ETH supplied for USD to be tracked - its a tricky balance between running into issues like this, and people manipulating pools and the data (which is not whats happening here). 

But maybe the threshold is too high and theres a different heuristic we can use. Will re-evaluate today.

**Comment by Pinatapins** [comment]
@ianlapham <https://github.com/ianlapham> Thank you for your reply.
Please let me know if there is anything that can be done on our hand.

Thanks. Regards

**Comment by Pinatapins** [comment]
Hi Ian,
We are still with the issue,
The PINS still shows 0,00$ price where few hundred thousands of dollars
have been transferred into pools,
Please let us know how we can fix this and if something can be done.

Thanks

**Comment by Pinatapins** [comment]
Hello,

We removed and re update the pool with more eth,
Please let us know if something can be done.
This issue is very problematic

Thanks.

**Comment by ianlapham** [comment]
Working on a change thatll track prices with a lower ETH threshold - this will take some time though.

**Comment by Pinatapins** [comment]
Ok, thanks for the update.

**Comment by Pinatapins** [comment]
Hello,
Are there any updates on this?
We are waiting for the update to launch our coin, without price performance
it's useless.
On the other hand, we tried opening a pair with usdt to check if that would
help but i did not, but is there a way to remove the pins/usdt closed pool?
we removed liquidity and it shows up with 0 TVL, just wondering...

Thank you,
Best regards.

**Comment by ianlapham** [comment]
This seems fixed now - see the accurate TVL number here https://info.uniswap.org/#/pools/0xb702ead3b0c34fddfa9b4229c981d56a868a5164
