### ISSUE TITLE
Liquidity tab looks buggy for USDT/USDC pair

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-v3-info#63]
**Bug Description**
Candle that has ~18M is much bigger than one that has ~40M of liquidity in it. 

**Steps to Reproduce**
https://info.uniswap.org/#/pools/0x6c6bc977e13df9b0de53b251522280bb72383700

![image](https://user-images.githubusercontent.com/40821065/119054318-b7e80a00-b9c7-11eb-9615-f9d3cfe2256c.png)
![image](https://user-images.githubusercontent.com/40821065/119054346-c2a29f00-b9c7-11eb-8b8b-62ac53d6488c.png)

**Expected Behavior**
Candles size represent liquidity in that range

**Additional Context**
jab in Discord thinks that everything is shifted by 1 position

**Comment by ianlapham** [comment]
@BOR4 Good find here - it seems like things are shifted by one tick  - will check on this
