### ISSUE TITLE
Wrong address displayed on "remove" list

### ISSUE THREAD

**Issue by reuptaken** [Uniswap/uniswap-v3-info#80]
**Bug Description**
Wrong address displayed on "remove" list (address of contract)

**Steps to Reproduce**
<img width="1199" alt="Zrzut ekranu 2021-05-25 o 09 52 05" src="https://user-images.githubusercontent.com/26765602/119460993-89f42400-bd3f-11eb-98d3-26b6c0be40e8.png">

Should display position owner address.

**Comment by ianlapham** [comment]
Good catch - fixing
