### ISSUE TITLE
Top Pools data showing 0

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-v3-info#90]
![image](https://user-images.githubusercontent.com/40821065/120118300-16647380-c192-11eb-9574-753cd9b3999a.png)

I think image says it all :)

Update: fixed after several refreshes. Seems one of those issues that gets resolved after hard refresh.

**Comment by willhennessy** [comment]
Thanks bor4! It seems to be fixed now. please flag if it comes up again
